# Generated by Django 4.2 on 2025-11-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_blogcategory_projectcategory_alter_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
