# Generated by Django 4.2 on 2025-11-17 19:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_testimonial_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="subtitle",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, max_length=1500
            ),
        ),
    ]
